### ISSUE TITLE
Sparkpost is undefined

### ISSUE THREAD

**Issue by fvpDev** [avrahamgoldman/sparkpost-api#1]
Hi! Would really love to use this, but I'm getting an error `Sparkpost` is undefined when attempting to use `new Sparkpost(...)`

Can you help me out?

**Comment by fvpDev** [comment]
Just now noticed...could it be I missed the capitalization and should try `new SparkPost()`? Oh no....

**Comment by fvpDev** [comment]
Nope...`[ReferenceError: SparkPost is not defined]`

**Comment by avigoldman** [comment]
Hey @fvpDev! Sorry to hear that you're running into some problems with this package. I would check to make sure that you imported the Sparkpost object. At the beginning of your file along with `import { Meteor } from 'meteor/meteor` add `import { Sparkpost } from 'meteor/agoldman:sparkpost-api';`. If you are still having trouble post a code sample and I'll try to debug it with you.

**Comment by fvpDev** [comment]
Thanks, that fixed it however I now I am running into a different issue; I used your example with my API key & email addresses and Sparkpost is returning a success message but I'm not receiving the email.

**Comment by fvpDev** [comment]
Also; will I be able to use this package like in this example?
https://github.com/SparkPost/node-sparkpost#send-an-email-hello-world-example

**Comment by avigoldman** [comment]
Yes, just make sure to follow this package's documentation for the request method found [here](https://github.com/avrahamgoldman/sparkpost-api/blob/master/README.md#requestmethod-endpoint-data-callback). Anything you can do with the `node-sparkpost` library you can do with this one.

**Comment by fvpDev** [comment]
Right, so according to your docs link and package code the only methods this package supports are `request | post | put | get | delete`.... which means you can't do everything like my example link (I tried). For some reason the post method takes Sparkpost forever (~few hours) to process and for me to receive the email so instead I am going to resort to importing `node-sparkpost` via `meteor npm install sparkpost` as Meteor 1.3 now supports npm packages directly.
